spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50000MB
      max-request-size: 50000MB



server:
  servlet:
    context-path: /api/v1/



springdoc:
  default-consumes-media-type: application/json

  swagger-ui:
    enabled: true
    path: /swagger-ui.html


projet:
  securite:
    jwtSecret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
    jwtExpiration: 86400000 # a day  avant 30
    jwtRefreshToken: 604800000 # 7 days avant 300


upload:
  path: /Users/macbook/Desktop/edacy/task_app_back/uploads/
  image: /Users/macbook/Desktop/edacy/task_app_back/uploads/


smtp:
  server:
    host: "smtp.gmail.com"
    from: "ablayefaye9725@gmail.com"
    password: "ovun lsxm arwo vwzz"

app:
  file:
    regex-splitter: '@##___@##'
  url:
    front: http://localhost:4200/#/auth

url:
  logo:
    starterkit: http://localhost:8085/static/logo-image.png

otp:
  expiration: 30
interval: PT30S
