package sn.ods.starterkit_spring.presentation.dto.responses;

/**
 * @author G2k R&D
 */

public enum Status {

    OK, BAD_REQUEST, UNAUTHORIZED, VALIDATION_EXCEPTION, EXCEPTION, WRONG_CREDENTIALS, ACCESS_DENIED,
    NOT_FOUND, DUPLICATE_ENTITY, DUPLICATE_EMAIL, DUPLICATE_REFERENCE, DUPLICATE_TELEPHONE, TOKEN_EXPIRED,
    FIRST_CONNECTION, DISABLED_ACCOUNT, INVALIDE_TOKEN, INVALIDE_URL, UNSUPPORTED_MEDIA_TYPE, DIRECTORY_NOT_FOUND, METHOD_NOT_ALLOWED

}
